name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Update NuGet
      run: nuget restore
    - name: Build
      run: dotnet build
    - name: Main Program Test
      run: packages\NUnit.ConsoleRunner.3.12.0\tools\nunit3-console.exe HSFMainUnitTest\bin\Debug\HSFMainUnitTest.dll
    - name: Scheduler Test
      run: packages\NUnit.ConsoleRunner.3.12.0\tools\nunit3-console.exe HSFSchedulerUnitTest\bin\Debug\HSFSchedulerUnitTest.dll
    - name: System Test
      run: packages\NUnit.ConsoleRunner.3.12.0\tools\nunit3-console.exe HSFSystemUnitTest\bin\Debug\HSFSystemUnitTest.dll
    - name: Universe Test
      run: packages\NUnit.ConsoleRunner.3.12.0\tools\nunit3-console.exe HSFUniverseUnitTest\bin\Debug\HSFUniverseUnitTest.dll
    - name: Mission Elements Test
      run: packages\NUnit.ConsoleRunner.3.12.0\tools\nunit3-console.exe HSFMissionElementsUnitTest\bin\Debug\HSFMissionElementsUnitTest.dll
    - name: User Model Test
      run: packages\NUnit.ConsoleRunner.3.12.0\tools\nunit3-console.exe HSFUserModelUnitTest\bin\Debug\HSFUserModelUnitTest.dll
    - name: Utilities Test
      run: packages\NUnit.ConsoleRunner.3.12.0\tools\nunit3-console.exe HSFUtilitiesUnitTest\bin\Debug\HSFUtilitiesTest.dll
      
# run: dotnet test --verbosity normal
